openapi: 3.0.3
info:
  title: Test Fraud Prevention Headers
  version: '1.0'
  description: |
    This API checks the fraud prevention headers on individual requests.
    
    See also [fraud prevention](https://developer.service.hmrc.gov.uk/guides/fraud-prevention).
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox

paths:
  /test/fraud-prevention-headers/validate:
    get:
      summary: Validate fraud prevention headers
      description: This resource validates fraud prevention headers submitted with this HTTP request.
      operationId: Validatefraudpreventionheaders
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      - $ref: '#/components/parameters/authorizationHeader'
      - $ref: '#/components/parameters/gov-client-connection-method'
      - $ref: '#/components/parameters/gov-client-device-id'
      - $ref: '#/components/parameters/gov-client-local-ips'
      - $ref: '#/components/parameters/gov-client-local-ips-timestamp'
      - $ref: '#/components/parameters/gov-client-mac-addresses'
      - $ref: '#/components/parameters/gov-client-multi-factor'
      - $ref: '#/components/parameters/gov-client-screens'
      - $ref: '#/components/parameters/gov-client-timezone'
      - $ref: '#/components/parameters/gov-client-user-agent'
      - $ref: '#/components/parameters/gov-client-user-ids'
      - $ref: '#/components/parameters/gov-client-window-size'
      - $ref: '#/components/parameters/gov-vendor-license-ids'
      - $ref: '#/components/parameters/gov-vendor-product-name'
      - $ref: '#/components/parameters/gov-vendor-version'
      - $ref: '#/components/parameters/gov-client-public-ip'
      - $ref: '#/components/parameters/gov-client-public-ip-timestamp'
      - $ref: '#/components/parameters/gov-client-public-port'
      - $ref: '#/components/parameters/gov-vendor-forwarded'
      - $ref: '#/components/parameters/gov-vendor-public-ip'
      - $ref: '#/components/parameters/gov-client-browser-js-user-agent'

      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/TestFraudPreventionHeadersValidateresponse'
              examples:
                noFphHeadersProvided:
                  description: No fraud prevention headers provided
                  value:
                    specVersion: '3.1'
                    code: INVALID_HEADERS
                    message: No fraud prevention headers submitted. These are required by law. Check the specification.
                allFphHeadersValid:
                  description: All fraud prevention headers appear to be valid
                  value:
                    specVersion: '3.1'
                    code: VALID_HEADERS
                    message: All headers required for your connection method have been supplied and all appear to be valid. Validation is based on a single request. We have access to all requests and can draw additional conclusions.
                someFphHeadersWithAdvisories:
                  description: Some fraud prevention headers where advisories are given
                  value:
                    specVersion: '3.1'
                    code: POTENTIALLY_INVALID_HEADERS
                    message: At least 1 header is potentially invalid
                    warnings:
                    - code: POTENTIALLY_INVALID_HEADER
                      message: Check you are using the correct Gov-Client-Connection-Method. Web applications do not usually provide the os field as browsers do not expose this information.
                      headers:
                      - gov-client-user-ids
                someFphHeadersInvalid:
                  description: Some fraud prevention headers may be invalid
                  value:
                    specVersion: '3.1'
                    code: INVALID_HEADERS
                    message: At least 1 header is invalid
                    errors:
                    - code: INVALID_HEADER
                      message: Value must be a recognised timezone in UTC format, submitted as UTC±<hh>:<mm>
                      headers:
                      - gov-client-timezone
                    - code: MISSING_HEADER
                      message: Header required
                      headers:
                      - gov-vendor-version
                    - code: INVALID_HEADERS
                      message: At least 1 pair of IPs in Gov-Vendor-Forwarded must include Gov-Client-Public-IP in the 'for' field and Gov-Vendor-Public-IP in the 'by' field. Check all 3 headers are consistent.
                      headers:
                      - gov-vendor-forwarded
                      - gov-vendor-public-ip
                      - gov-client-public-ip
                    warnings:
                    - code: POTENTIALLY_INVALID_HEADER
                      message: Check you are using the correct Gov-Client-Connection-Method. Web applications do not usually provide the os field as browsers do not expose this information.
                      headers:
                      - gov-client-user-ids
      deprecated: false
      security:
        - Application-Restricted: []

  /test/fraud-prevention-headers/{api}/validation-feedback:
    get:
      summary: Get feedback on requests made to an API
      description: Use this resource to get feedback on fraud prevention headers submitted by your application in sandbox. You'll get detailed feedback on the most recent request to each endpoint of a supported API.
      operationId: GetfeedbackonrequestsmadetoanAPI
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      - $ref: '#/components/parameters/authorizationHeader'
      - name: api
        in: path
        description: Identifies the API to get feedback on.
        required: true
        style: simple
        schema:
          allOf:
          - $ref: '#/components/schemas/apiIdentifier'
          - description: Identifies the API to get feedback on.
      - name: connectionMethod
        in: query
        description: If your application uses more than 1 connection method, you can use this query parameter to filter by connection method.
        style: form
        explode: true
        schema:
          allOf:
          - $ref: '#/components/schemas/connectionMethod'
          description: If your application uses more than 1 connection method, you can use this query parameter to filter by connection method.
          example: DESKTOP_APP_DIRECT
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/TestFraudPreventionHeadersValidationFeedbackresponse'
                example:
                  requests:
                  - path: /organisations/vat/107794340/liabilities
                    method: GET
                    requestTimestamp: 2020-09-21T10:30:05.962Z
                    code: INVALID_HEADERS
                    headers:
                    - header: gov-client-connection-method
                      value: DESKTOP_APP_VIA_SERVER
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-device-id
                      value: beec798b-b366-47fa-b1f8-92cede14a1ce
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-local-ips
                      value: 10.1.2.3,10.3.4.2
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-local-ips-timestamp
                      value: 2020-09-21T10:30:05.123Z
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-mac-addresses
                      code: MISSING_HEADER
                      errors:
                      - Header required
                      warnings: []
                    - header: gov-client-multi-factor
                      value: type=AUTH_CODE&timestamp=2017-04-21T13%3A23Z&unique-reference=c672b8d1ef56ed28,type=TOTP&timestamp=2017-05-19T13%3A10Z&unique-reference=ac73430ffdfd9
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-public-ip
                      value: 198.51.100.0
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-public-ip-timestamp
                      value: 2020-09-21T10:30:05.123Z
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-public-port
                      value: '12345'
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-screens
                      value: width=1920&height=1080
                      code: INVALID_HEADER
                      errors:
                      - At least 1 screen is missing a value for scaling factor
                      - At least 1 screen is missing a value for colour depth
                      warnings: []
                    - header: gov-client-timezone
                      value: UTC+00:00
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-user-agent
                      value: os-family=Windows&os-version=Server%202012&device-manufacturer=Dell%20Inc.&device-model=OptiPlex%20980
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-user-ids
                      value: os=user123
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-client-window-size
                      value: width=1256&height=803
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-vendor-forwarded
                      value: by=203.0.113.6&for=198.51.100.0
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-vendor-license-ids
                      value: my%20licensed%20software=8D7963490527D33716835EE7C195516D5E562E03B224E9B359836466EE40CDE1
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-vendor-public-ip
                      value: 203.0.113.6
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-vendor-product-name
                      value: Product%20Name
                      code: VALID_HEADER
                      errors: []
                      warnings: []
                    - header: gov-vendor-version
                      value: my-desktop-app=2.2.2
                      code: POTENTIALLY_INVALID_HEADER
                      errors: []
                      warnings:
                      - For client server architectures, submit a version for the client and the server. For all other architectures, submit at least 1 version.
                    crossValidation:
                    - headers:
                      - gov-vendor-forwarded
                      - gov-vendor-public-ip
                      - gov-client-public-ip
                      code: VALID_HEADERS
                      errors: []
              example:
                requests:
                - path: /organisations/vat/107794340/liabilities
                  method: GET
                  requestTimestamp: 2020-09-21T10:30:05.962Z
                  code: INVALID_HEADERS
                  headers:
                  - header: gov-client-connection-method
                    value: DESKTOP_APP_VIA_SERVER
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-device-id
                    value: beec798b-b366-47fa-b1f8-92cede14a1ce
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-local-ips
                    value: 10.1.2.3,10.3.4.2
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-local-ips-timestamp
                    value: 2020-09-21T10:30:05.123Z
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-mac-addresses
                    code: MISSING_HEADER
                    errors:
                    - Header required
                    warnings: []
                  - header: gov-client-multi-factor
                    value: type=AUTH_CODE&timestamp=2017-04-21T13%3A23Z&unique-reference=c672b8d1ef56ed28,type=TOTP&timestamp=2017-05-19T13%3A10Z&unique-reference=ac73430ffdfd9
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-public-ip
                    value: 198.51.100.0
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-public-ip-timestamp
                    value: 2020-09-21T10:30:05.123Z
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-public-port
                    value: '12345'
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-screens
                    value: width=1920&height=1080
                    code: INVALID_HEADER
                    errors:
                    - At least 1 screen is missing a value for scaling factor
                    - At least 1 screen is missing a value for colour depth
                    warnings: []
                  - header: gov-client-timezone
                    value: UTC+00:00
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-user-agent
                    value: os-family=Windows&os-version=Server%202012&device-manufacturer=Dell%20Inc.&device-model=OptiPlex%20980
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-user-ids
                    value: os=user123
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-client-window-size
                    value: width=1256&height=803
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-vendor-forwarded
                    value: by=203.0.113.6&for=198.51.100.0
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-vendor-license-ids
                    value: my%20licensed%20software=8D7963490527D33716835EE7C195516D5E562E03B224E9B359836466EE40CDE1
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-vendor-public-ip
                    value: 203.0.113.6
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-vendor-product-name
                    value: Product%20Name
                    code: VALID_HEADER
                    errors: []
                    warnings: []
                  - header: gov-vendor-version
                    value: my-desktop-app=2.2.2
                    code: POTENTIALLY_INVALID_HEADER
                    errors: []
                    warnings:
                    - For client server architectures, submit a version for the client and the server. For all other architectures, submit at least 1 version.
                  crossValidation:
                  - headers:
                    - gov-vendor-forwarded
                    - gov-vendor-public-ip
                    - gov-client-public-ip
                    code: VALID_HEADERS
                    errors: []
      deprecated: false
      security:
        - Application-Restricted: []
components:
  parameters:
    acceptHeader:
      name: Accept
      description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
      in: header
      required: true
      schema:
        type: string
        example: >-
          application/vnd.hmrc.1.0+json
    authorizationHeader:
      name: Authorization
      description: An [OAuth 2.0 Bearer Token](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints)
      in: header
      required: true
      schema:
        type: string
        example: >-
          Bearer 59fc92c1cdf0b8ef1f138a702effdbd2

    # https://developer.service.hmrc.gov.uk/guides/fraud-prevention/
    # generated with make in tools/utils/
    gov-client-connection-method:
      name: Gov-Client-Connection-Method
      description: TBD
      in: header
      schema:
        type: string
        enum:
        - MOBILE_APP_DIRECT
        - MOBILE_APP_VIA_SERVER
        - DESKTOP_APP_VIA_SERVER
        - BATCH_PROCESS_DIRECT
        - DESKTOP_APP_DIRECT
        - WEB_APP_VIA_SERVER
    gov-client-device-id:
      name: Gov-Client-Device-ID
      description: An identifier unique to the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: beec798b-b366-47fa-b1f8-92cede14a1ce
    gov-client-local-ips:
      name: Gov-Client-Local-IPs
      description: A list of all local IPv4 and IPv6 addresses available to the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: 10.1.2.3,10.3.4.2
        name1:
          value: fc00%3A%3A,10.1.2.3
    gov-client-local-ips-timestamp:
      name: Gov-Client-Local-IPs-Timestamp
      description: A timestamp to show when Gov-Client-Local-IPs is collected.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: 2020-09-21T14:30:05.123Z
    gov-client-mac-addresses:
      name: Gov-Client-MAC-Addresses
      description: The list of MAC addresses available on the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: ea%3A43%3A1a%3A5d%3A21%3A45,10%3A12%3Acc%3Afa%3Aaa%3A32
    gov-client-multi-factor:
      name: Gov-Client-Multi-Factor
      description: A list of key-value data structures containing details of the multi-factor authentication (MFA) statuses related to the API call.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: type=AUTH_CODE&timestamp=2021-11-21T13%3A23Z&unique-reference=fc4b5fd6816f75a7c81fc8eaa9499d6a299bd803397166e8c4cf9280b801d62c,type=TOTP&timestamp=2021-11-21T13%3A20Z&unique-reference=0283da60063abfb3a87f1aed845d17fe2d9ba8c780b478dc4ae048f5ee97a6d5
    gov-client-screens:
      name: Gov-Client-Screens
      description: Information about the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: width=375&height=812&scaling-factor=2&colour-depth=32
        name1:
          value: width=1920&height=1080&scaling-factor=1&colour-depth=16,width=3000&height=2000&scaling-factor=1.25&colour-depth=16
    gov-client-timezone:
      name: Gov-Client-Timezone
      description: The local timezone of the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: UTC+00:00
        name1:
          value: UTC+01:00
        name2:
          value: UTC-01:15
    gov-client-user-agent:
      name: Gov-Client-User-Agent
      description: Identifies the operating system and device.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: os-family=Windows&os-version=Server%202012&device-manufacturer=Dell%20Inc.&device-model=OptiPlex%20980
        name1:
          value: os-family=iOS&os-version=13.3.1&device-manufacturer=Apple&device-model=iPhone12%2C3
    gov-client-user-ids:
      name: Gov-Client-User-IDs
      description: A key-value data structure containing user identifiers.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: os=domain%5Calice&my-application=alice123
        name1:
          value: os=domain%5Calice&my-application=alice123&my-secondary-application=alice_secondary
        name2:
          value: my-application=alice123
        name3:
          value: os=domain%5Calice
    gov-client-window-size:
      name: Gov-Client-Window-Size
      description: The width and height of the window (in pixels) on the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: width=1256&height=803
        name1:
          value: width=375&height=812
    gov-vendor-license-ids:
      name: Gov-Vendor-License-IDs
      description: A key-value data structure of hashed license keys relating to the vendor software initiating the API request on the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: my-licensed-software=8D7963490527D33716835EE7C195516D5E562E03B224E9B359836466EE40CDE1
    gov-vendor-product-name:
      name: Gov-Vendor-Product-Name
      description: The name of the product marketed to end users.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: Company%20Name
        name1:
          value: Product%20Name
    gov-vendor-version:
      name: Gov-Vendor-Version
      description: A key-value data structure of versions of your software involved in handling a request.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: my-mobile-app=2.2.2&my-serverside-code=v3.8
        name1:
          value: my-web-app=2.2.2
        name2:
          value: my-application=1.6.0
        name3:
          value: my-desktop-app=2.2.2&my-serverside-code=v3.8
    gov-client-public-ip:
      name: Gov-Client-Public-IP
      description: The public IPv4 or IPv6 address from which the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: ABCD:EF01:2345:6789:ABCD:EF01:2345:6789
        name1:
          value: 198.51.100.0
    gov-client-public-ip-timestamp:
      name: Gov-Client-Public-IP-Timestamp
      description: A timestamp to show when Gov-Client-Public-IP is collected.
      in: header
      schema:
        type: string
      examples:
        name0:
          value: 2020-09-21T14:30:05.123Z
    gov-client-public-port:
      name: Gov-Client-Public-Port
      description: The public TCP port used by the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: 12345
    gov-vendor-forwarded:
      name: Gov-Vendor-Forwarded
      description: A list that details hops over the internet between services that terminate Transport Layer Security (TLS).
      in: header
      schema:
        type: string
      examples:
        name0:
          value: by=203.0.113.6&for=198.51.100.0
        name1:
          value: by=2001%3A0db8%3A85a3%3A0000%3A0000%3A8a2e%3A0370%3A7334&for=198.51.100.0,by=203.0.113.6&for=2001%3A0db8%3A85a3%3A0000%3A0000%3A8a2e%3A0370%3A7334,by=176.30.57.118&for=203.0.113.6
    gov-vendor-public-ip:
      name: Gov-Vendor-Public-IP
      description: The public IP address of the servers the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: 203.0.113.6
    gov-client-browser-js-user-agent:
      name: Gov-Client-Browser-JS-User-Agent
      description: JavaScript-reported user agent string from the 
      in: header
      schema:
        type: string
      examples:
        name0:
          value: Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405

  securitySchemes:
    Application-Restricted:
      type: oauth2
      description: |
        This endpoint is [application-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints) and requires an Authorization header containing an OAuth 2.0 Bearer Token.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: {}
  schemas:
    apiIdentifier:
      enum:
      - business-details-mtd
      - business-income-source-summary-mtd
      - business-source-adjustable-summary-mtd
      - cis-deductions-mtd
      - individual-calculations-mtd
      - individual-losses-mtd
      - individuals-business-end-of-period-statement-mtd
      - individuals-charges-mtd
      - individuals-disclosures-mtd
      - individuals-expenses-mtd
      - individuals-income-received-mtd
      - individuals-reliefs-mtd
      - individuals-state-benefits-mtd
      - obligations-mtd
      - other-deductions-mtd
      - property-business-mtd
      - self-assessment-mtd
      - self-assessment-accounts-mtd
      - self-assessment-assist-mtd
      - self-employment-business-mtd
      - vat-mtd
      - individuals-capital-gains-income-mtd
      - individuals-dividends-income-mtd
      - individuals-employments-income-mtd
      - individuals-foreign-income-mtd
      - individuals-insurance-policies-income-mtd
      - individuals-other-income-mtd
      - individuals-pensions-income-mtd
      - individuals-savings-income-mtd
      - self-assessment-individual-details-mtd
      type: string
    connectionMethod:
      enum:
      - BATCH_PROCESS_DIRECT
      - DESKTOP_APP_DIRECT
      - DESKTOP_APP_VIA_SERVER
      - MOBILE_APP_DIRECT
      - MOBILE_APP_VIA_SERVER
      - OTHER_DIRECT
      - OTHER_VIA_SERVER
      - WEB_APP_VIA_SERVER
      type: string
    errorResponse:
      title: errorResponse
      required:
      - code
      type: object
      properties:
        code:
          type: string
    Code:
      title: VALID_HEADERS
      enum:
      - VALID_HEADERS
      type: string
      description: basic checks show that the header value supplied appears to be valid.
    Code1:
      title: INVALID_HEADERS
      enum:
      - INVALID_HEADERS
      type: string
      description: basic checks show that at least 1 of the header values supplied is not valid.
    Code2:
      title: POTENTIALLY_INVALID_HEADERS
      enum:
      - POTENTIALLY_INVALID_HEADERS
      type: string
      description: basic checks show that at least 1 of the header values supplied is potentially invalid as per the current specification.
    Code3:
      title: INVALID_HEADER
      enum:
      - INVALID_HEADER
      type: string
      description: basic checks show that the header value supplied is not valid.
    Code4:
      title: POTENTIALLY_INVALID_HEADER
      enum:
      - POTENTIALLY_INVALID_HEADER
      type: string
      description: basic checks show that the header value supplied is potentially invalid as per the current specification.
    Code5:
      title: VALID_HEADERS
      enum:
      - VALID_HEADERS
      type: string
      description: basic checks show that the header values supplied appear to be valid.
    Code6:
      title: VALID_HEADER
      enum:
      - VALID_HEADER
      type: string
      description: basic checks show that the header value supplied is valid.
    Code7:
      title: VALID_HEADERS
      enum:
      - VALID_HEADERS
      type: string
      description: cross checks identified no problems with the headers.
    Code32:
      title: MISSING_HEADER
      enum:
      - MISSING_HEADER
      type: string
      description: header required for the connection method is not supplied.
    Code33:
      title: EMPTY_HEADER
      enum:
      - EMPTY_HEADER
      type: string
      description: header required for the connection method is empty.
    Code41:
      title: UNEXPECTED_HEADER
      enum:
      - UNEXPECTED_HEADER
      type: string
      description: header value supplied is not a fraud prevention header, or the fraud prevention header is not spelt correctly.
    Code51:
      title: INVALID_HEADERS
      enum:
      - INVALID_HEADERS
      type: string
      description: at least 1 of the header values supplied is not valid, check errors and warnings.
    Code52:
      title: POTENTIALLY_INVALID_HEADERS
      enum:
      - POTENTIALLY_INVALID_HEADERS
      type: string
      description: at least 1 of the header values supplied is potentially invalid, check warnings.
    Code53:
      title: NO_HEADERS
      enum:
      - NO_HEADERS
      type: string
      description: the request did not have any fraud prevention headers.
    Code61:
      title: INVALID_HEADER
      enum:
      - INVALID_HEADER
      type: string
      description: the header value supplied is not valid, check errors and warnings.
    Code62:
      title: POTENTIALLY_INVALID_HEADER
      enum:
      - POTENTIALLY_INVALID_HEADER
      type: string
      description: the header value supplied is potentially invalid, check warnings.
    Code64:
      title: UNEXPECTED_HEADER
      enum:
      - UNEXPECTED_HEADER
      type: string
      description: header is not needed for the connection method, is not a fraud prevention header, or is not spelt correctly.
    Code65:
      title: TEST_SCENARIO_HEADER
      enum:
      - TEST_SCENARIO_HEADER
      type: string
      description: header is used in sandbox testing to trigger different test scenarios.
    Code71:
      title: INVALID_HEADERS
      enum:
      - INVALID_HEADERS
      type: string
      description: cross checks identified one or more problems with the headers, check errors.
    CrossValidation:
      title: CrossValidation
      required:
      - headers
      - code
      - errors
      type: object
      properties:
        headers:
          type: array
          items:
            type: string
          description: A list of the headers included in the validation.
        code:
          oneOf:
          - $ref: '#/components/schemas/Code7'
          - $ref: '#/components/schemas/Code71'
          description: A machine-readable code indicating the result of cross validation.
        errors:
          type: array
          items:
            type: string
          description: A list of error messages resulting from cross validation of header values.
    Error:
      title: Error
      required:
      - code
      - message
      - headers
      type: object
      properties:
        code:
          oneOf:
          - $ref: '#/components/schemas/Code3'
          - $ref: '#/components/schemas/Code1'
          - $ref: '#/components/schemas/Code32'
          - $ref: '#/components/schemas/Code33'
          description: A machine-readable code indicating the type of error.
        message:
          type: string
          description: A description of the error.
        headers:
          minItems: 1
          type: array
          items:
            type: string
          description: A list of headers that have the error.
    Header:
      title: Header
      required:
      - header
      - code
      - errors
      - warnings
      type: object
      properties:
        header:
          type: string
          description: The name of the header.
        value:
          type: string
          description: The value submitted for this header.
        code:
          oneOf:
          - $ref: '#/components/schemas/Code6'
          - $ref: '#/components/schemas/Code61'
          - $ref: '#/components/schemas/Code62'
          - $ref: '#/components/schemas/Code32'
          - $ref: '#/components/schemas/Code64'
          - $ref: '#/components/schemas/Code65'
          description: A machine-readable code indicating the validation result for the header.
        errors:
          type: array
          items:
            type: string
          description: A list of error messages in the validation result for the header value.
        warnings:
          type: array
          items:
            type: string
          description: A list of warning messages in the validation result for the header value.
      description: ''
    Request:
      title: Request
      required:
      - path
      - method
      - requestTimestamp
      - code
      - headers
      - crossValidation
      type: object
      properties:
        path:
          type: string
          description: The path the request was submitted to.
        method:
          type: string
          description: The HTTP method used for the request.
        requestTimestamp:
          type: string
          description: The timestamp of when the request was submitted.
        code:
          oneOf:
          - $ref: '#/components/schemas/Code5'
          - $ref: '#/components/schemas/Code51'
          - $ref: '#/components/schemas/Code52'
          - $ref: '#/components/schemas/Code53'
          description: A machine-readable code indicating the validation result for the request.
        headers:
          type: array
          items:
            $ref: '#/components/schemas/Header'
          description: 'A list containing each of the Gov-* headers submitted with the request.'
        crossValidation:
          type: array
          items:
            $ref: '#/components/schemas/CrossValidation'
          description: A list of validations involving multiple headers.
      description: ''
    TestFraudPreventionHeadersValidateresponse:
      title: TestFraudPreventionHeadersValidateresponse
      required:
      - specVersion
      - message
      - code
      type: object
      properties:
        specVersion:
          type: string
          description: The version of fraud prevention headers specification that the request was validated against. This value will change when a major version of the specification is released.
        message:
          type: string
          description: A summary of the overall outcome of the fraud prevention header checks.
        code:
          oneOf:
          - $ref: '#/components/schemas/Code'
          - $ref: '#/components/schemas/Code1'
          - $ref: '#/components/schemas/Code2'
          description: A machine-readable code showing the overall validation result.
        errors:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: ''
        warnings:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Warning'
          description: ''
      description: Test Fraud Prevention Headers Response
    TestFraudPreventionHeadersValidationFeedbackresponse:
      title: TestFraudPreventionHeadersValidationFeedbackresponse
      required:
      - requests
      type: object
      properties:
        requests:
          type: array
          items:
            $ref: '#/components/schemas/Request'
          description: 'A list containing feedback on the latest request submitted to each API endpoint.'
      description: API request validation feedback
    Warning:
      title: Warning
      required:
      - code
      - message
      - headers
      type: object
      properties:
        code:
          oneOf:
          - $ref: '#/components/schemas/Code4'
          - $ref: '#/components/schemas/Code33'
          - $ref: '#/components/schemas/Code41'
          description: A machine-readable code indicating the type of error.
        message:
          type: string
          description: A description of the error.
        headers:
          minItems: 1
          type: array
          items:
            type: string
          description: A list of headers that have the advisory.
tags:
- name: test-fraud-prevention-headers
  description: ''
